# Generated by Django 4.1.1 on 2022-11-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzamenu',
            name='cost',
            field=models.IntegerField(verbose_name='Стоимость'),
        ),
    ]
