# Generated by Django 4.1.1 on 2022-12-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaShop', '0003_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(max_length=50, verbose_name='Логин'),
        ),
    ]
