# Generated by Django 4.1.1 on 2022-12-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaShop', '0004_alter_users_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(default='Member', max_length=30, verbose_name='Роль'),
        ),
    ]
