# Generated by Django 4.1.1 on 2023-03-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaShop', '0007_pizzaorders_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzamenu',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='Фото'),
        ),
    ]
